name: Learn basic of GitHub Action

on:
  push:
    branches:
      -  main

jobs:
  Hello-World:
    runs-on: ubuntu-latest

    steps:
      - name: print hellow
        run: echo "hello world !!"
      - name: print hellow
        run: echo "hello world !!"
        
  
  chalo-World:
    runs-on: ubuntu-latest
    
    steps:
      - name: print chello
        run: cat /etc/os-release
